// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqafouknuhnjkufqxzqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxYWZvdWtudWhuamt1ZnF4enFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEyMjgsImV4cCI6MjA2NTQ2NzIyOH0.ok3HsysIvitoK_naVLChEhxSdVS3zbE8ERa9m61nezI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);